/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeConstraint } from './timeConstraint';
import { PitstopConstraint } from './pitstopConstraint';


export interface RouteRequestConstraints { 
    stopForFood?: boolean;
    preferIndoors?: boolean;
    avoidCrowds?: boolean;
    pitstops?: Array<PitstopConstraint>;
    timeConstraint?: TimeConstraint;
}

