/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.capybara.CapybaraCampusCrawlBackend.Controllers;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import com.capybara.CapybaraCampusCrawlBackend.Models.GraphEdge;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-03-18T22:02:47.023914Z[Etc/UTC]")
@Validated
public interface GraphEdgesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /graph-edges/
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getGraphs",
        tags = { "Graph Controller" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  GraphEdge.class)))
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/graph-edges/",
        produces = {"application/json", "text/xml"}
    )
    default ResponseEntity<List<GraphEdge>> getGraphs(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("*/*"))) {
                    String exampleString = "{ \"fromNode\" : { \"latitude\" : 0.8008281904610115, \"description\" : \"description\", \"nodeID\" : 1, \"longitude\" : 6.027456183070403 }, \"edgeId\" : 0, \"bidirectional\" : true, \"distance\" : 6.027456183070403, \"toNode\" : { \"latitude\" : 0.8008281904610115, \"description\" : \"description\", \"nodeID\" : 1, \"longitude\" : 6.027456183070403 }, \"fromToAction\" : \"fromToAction\", \"pathshape\" : \"pathshape\", \"toFromAction\" : \"toFromAction\" }";
                    ApiUtil.setExampleResponse(request, "*/*", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
